spring:
  application:
    name: web-application
  jmx:
    enabled: false
    
server:
  port: 8090
  
eureka:
  instance:
    instanceId: ${spring.application.name}:${vcap.application.instance_id:${spring.application.instance_id:${random.value}}}
  client:
    healthcheck:
      enabled: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://administrator:password@eureka0pri.netsgroup.com:8761/eureka/

feign:  httpclient:    enabled: true
  okhttp:    enabled: false
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
        loggerLevel: full
          
management:
  endpoint:
    health:
      enabled: true
    info:
      enabled: true
