spring:
  application:
    name: web-application
  jmx:
    enabled: false
    
server:
  port: 8090
  address: cloud.netsgroup.com
  servlet:
    context-path: /waa
  use-forward-headers: true
  tomcat:
    remote-ip-header: x-forwarded-for
    protocol-header: x-forwarded-proto
#  address: cloud.netsgroup.com
  ssl:
    enabled: true
    client-auth: none
    key-store: classpath:cloud_certificate.jks
    key-store-password: 123456
    trust-store: classpath:cloud_certificate.jks
    trust-store-password: 123456
    
eureka:
  instance:
    hostname: cloud.netsgroup.com
    nonSecurePortEnabled: false
    securePortEnabled: true
    securePort: ${server.port}
    instanceId: ${spring.application.name}:${vcap.application.instance_id:${spring.application.instance_id:${random.value}}}
    statusPageUrl: https://${server.address}:${server.port}/actuator/info
    healthCheckUrl: https://${server.address}:${server.port}/actuator/health
    homePageUrl: https://${server.address}:${server.port}
  client:
    initial-instance-info-replication-interval-seconds: 2
    eureka-connection-idle-timeout-seconds: 5
    eureka-service-url-poll-interval-seconds: 2
    instance-info-replication-interval-seconds: 5
    registry-fetch-interval-seconds: 5
    should-enforce-registration-at-init: true   
    healthcheck:
      enabled: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: https://administrator:password@${eureka.instance.hostname}:8761/eureka/

feign:  httpclient:    enabled: true
  okhttp:    enabled: false
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
        loggerLevel: full
  ngs:
    interceptor:
      enable: true
      key: 123456
      key-type: secret
      header-name: X-NGS-AUTH
    filter:
      enable: false 
logging:
  level:
    root: info
    com.netflix.discovery: OFF                
management:
  endpoint:
    health:
      enabled: true
    info:
      enabled: true
