spring:  application:    name: eureka-server  jmx:    enabled: false  security:    user:      name: administrator      password: password  
server:
  port: 8761
  address: 0.0.0.0  ssl:    enabled: true    client-auth: none    key-store: classpath:cloud_certificate.jks    key-store-password: 123456    trust-store: classpath:cloud_certificate.jks    trust-store-password: 123456
  
eureka:
  instance:
    hostname: cloud.netsgroup.com    securePort: ${server.port}    securePortEnabled: true      nonSecurePortEnabled: false     homePageUrl: https://${eureka.instance.hostname}:${server.port}/    statusPageUrl: https://${eureka.instance.hostname}:${server.port}/admin/info  server:    wait-time-in-ms-when-sync-empty: 0
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${spring.security.user.name}:${spring.security.user.password}@${eureka.instance.hostname}:${server.port}/eureka/